package nl.airsupplies.utilities.gui;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;

import org.jetbrains.annotations.Nullable;

/**
 * @author Mark Jeronimus
 */
// Created 2017-09-22
public class ExceptionPanel extends JPanel {
	/**
	 * Creates new form ExceptionPanel
	 */
	public ExceptionPanel() {
		initComponents();
	}

	// @formatter:off
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	// <editor-fold desc="initComponents()"> //GEN-BEGIN:initComponents
	private void initComponents() {

        titleLabel = new JLabel();
        subtitleLabel = new JLabel();
        exceptionTextScrollPane = new JScrollPane();
        exceptionTextArea = new JTextArea();

        titleLabel.setText("Exception message");

        subtitleLabel.setText("Subtitle");

        exceptionTextScrollPane.setViewportView(exceptionTextArea);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(exceptionTextScrollPane, GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(titleLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtitleLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titleLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exceptionTextScrollPane, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
    }
	// </editor-fold>//GEN-END:initComponents
	// @formatter:on

	public void setTitle(String title) {
		titleLabel.setText(title);
	}

	public void setSubtitle(String subtitle) {
		subtitleLabel.setText(subtitle);
	}

	public void setDetailMessage(@Nullable String detailMessage) {
		exceptionTextScrollPane.setVisible(detailMessage != null);
		exceptionTextArea.setText(detailMessage == null ? "" : detailMessage);
		exceptionTextArea.setCaretPosition(0);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextArea exceptionTextArea;
    private JScrollPane exceptionTextScrollPane;
    private JLabel subtitleLabel;
    private JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
